version: "3.3"
services: 
  neo4j:
    image: neo4j:latest
    container_name: neo4j-map
    restart: always
    volumes:
      - "./neo4j/data:/data/"
      - "./neo4j/logs:/logs/"
    networks:
      net:
        ipv4_address: 172.22.0.2
    ports:
      - "7474:7474"
      - "7687:7687"
    env_file:
      - "./neo4j/env.neo4j"

  ors-app:
    container_name: ors-app
    restart: always
    ports:
      - "8081:8080"
      - "9001:9001"
    image: openrouteservice/openrouteservice:latest
    user: "${UID:-0}:${GID:-0}"
#    build:
#      context: ../
#      args:
#        ORS_CONFIG: ./openrouteservice/src/main/resources/ors-config-sample.json
#        OSM_FILE: ./openrouteservice/src/main/files/heidelberg.osm.gz
    volumes:
      - ./openrouteservice/graphs:/home/ors/ors-core/data/graphs
      - ./openrouteservice/elevation_cache:/home/ors/ors-core/data/elevation_cache
      - ./openrouteservice/logs/ors:/home/ors/ors-core/logs/ors
      - ./openrouteservice/logs/tomcat:/home/ors/tomcat/logs
      - ./openrouteservice/conf:/home/ors/ors-conf
      - ./openrouteservice/spain-latest.osm.pbf:/home/ors/ors-core/data/osm_file.pbf
    environment:
      - BUILD_GRAPHS=true  # Forces the container to rebuild the graphs, e.g. when PBF is changed
      - "JAVA_OPTS=-Djava.awt.headless=true -server -XX:TargetSurvivorRatio=75 -XX:SurvivorRatio=64 -XX:MaxTenuringThreshold=3 -XX:+UseG1GC -XX:+ScavengeBeforeFullGC -XX:ParallelGCThreads=4 -Xms3g -Xmx5g"
      - "CATALINA_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9001 -Dcom.sun.management.jmxremote.rmi.port=9001 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost"

  opentopodata:
    container_name: opentopodata
    restart: always
    build: "./opentopodata-master"
    ports:
      - "5000:5000"
    volumes:
      - ./opentopodata-master/data:/app/data:ro

networks:
  net:
    driver: bridge
    ipam:
     config:
       - subnet: 172.22.0.0/16
